added encryptor.py
glebssha/ciphers pull request #1
Opened 2020-04-17 20:42 UTC by GlebShabuldaev

2020-04-19 10:37 UTC, pkositsyn requested changes
В общем норм, только бы немного больше понимания, к чему тут классы. Вообще в идеале шифры должны наследоваться от базового для удобства работы с кодированием/декодированием

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +        self.u_e = {x: self.u_e.index(x) for x in self.u_e}
Сделай нормальные говорящие названия

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +        self.blank = ' \n\t'
string.whitespace

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +    def case(self, symbol: str, alph: list) -> int:
list нельзя, надо typing.List[str], это говорит о типе лежащих в списке переменных

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +            return 0
Сделай enum, то есть класс, в котором будут поля, отвечающие за состояние. См пример в семинаре по библиотекам

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +            print("ERROR: Unknown symbol")
И еще бы вывести сам символ

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +    def case(self, symbol: str, alph: list) -> int:
Надо лучше назвать функцию, плохо отражает суть

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +                return k
Это явно не функция, которая должна быть в классе алфавита

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +                return k
можно перенести ее в файл utils.py

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +            if symbol in alph[i]:
Итерируйся по объектам, а не индексам

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +        else:
Он лишний, учитывая return

2020-04-19 10:37 UTC, pkositsyn commented on caesar.py
> +            k = int(key) % n_1
Давай нормальные названия

2020-04-19 10:37 UTC, pkositsyn commented on caesar.py
> +    def do_caesar(m: int, word: str, key: Union[int, str]) -> str:
Странная связка, зачем тогда вообще класс? В нем надо бы ключ полем сделать

2020-04-19 10:37 UTC, pkositsyn commented on caesar.py
> +            c = Alphabet().case(symbol, alph)             # Register of a symbol
Создай инстанс класса, зачем каждый раз новый дергать

2020-04-19 10:37 UTC, pkositsyn commented on alphabet.py
> +        self.ru = [self.l_r, self.u_r, self.punc, self.blank, self.N_r]
Тут лучше подойдет NamedTuple

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +    return modes.get(mode, "Invalid operation")
Не стоит мешать инты со строкой

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +    }
Тут бы тоже enum

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +    """Determines which operation is going to be handeled"""
handled

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +            model = json.load(f)
Чуть лучше делать через pickle, в документации есть об этом

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +        with open(args.model_file, "w") as f:
Лучше на всякий случай от ошибок поменять порядок if

2020-04-19 10:37 UTC, pkositsyn commented on encryptor.py
> +mode = mode_get(args.mode)
Сделай точку входа `if _name__ == '__main__': main()`
def main():
...

2020-04-19 10:37 UTC, pkositsyn commented on hack.py
> +    def compare(dic1: dict, dic2: dict) -> int:
typing.Dict[key_type, value_type]

2020-04-19 10:37 UTC, pkositsyn commented on hack.py
> +                sum += (dic1[symbol])**2
Это можно обойти, если использовать defaultdict

2020-04-19 10:37 UTC, pkositsyn commented on train.py
> +        for i in range(len(text)):
Итерируйся по объектам

2020-04-19 10:37 UTC, pkositsyn commented on train.py
> +            dic[symbol] = count[symbol] / len(text)
А если len(text) = 0?

2020-04-19 10:37 UTC, pkositsyn commented on vigenere.py
> +    def do_vigenere(self, m: int, word: str, key: str) -> str:
Вроде неплохо, но можно было бы поддержать консистентность с Цезарем и сделать одинаковые функции с наследованием от базового класса

2020-05-01 13:05 UTC, glebssha commented on alphabet.py
> +            return 0
Не совсем понимаю как тут использовать enum, у меня неизвестный алфавит( eсли ставить тип alph как name, а числа как value)

2020-05-04 19:17 UTC, pkositsyn requested changes

2020-05-04 19:17 UTC, pkositsyn commented on alphabet.py
> +            print("ERROR: Unknown symbol %s" % (symbol))
f-string -  более современный стиль

2020-05-04 19:17 UTC, pkositsyn commented on encryptor.py
> +    hack = 3
константы UPPER_CASE

2020-05-04 19:17 UTC, pkositsyn commented on encryptor.py
> +    if mode == 2:
Mode(mode) == Mode.TRAIN

2020-05-04 19:17 UTC, pkositsyn commented on encryptor.py
> +    if mode == 1 or mode == -1:
in (encode, decode)

2020-05-04 19:17 UTC, pkositsyn commented on encryptor.py
> +            write_text(do_caesar(mode, word, args.key), mode)
не понял куда убрал класс. Надо было оставить, только функции тут и в виженере do назвать. нет смысла дублировать название класса

2020-05-04 19:17 UTC, pkositsyn commented on hack.py
> +            dic2 = defaultdict(lambda: 0, dic2)
dic2 зачем в конце?

2020-05-11 08:30 UTC, pkositsyn approved these changes

2020-05-11 08:30 UTC, pkositsyn commented on alphabet.py
> +    def get_lang(self, symbol: str) -> list:
Было правильно, исправил на неправильно

2020-05-11 08:30 UTC, pkositsyn commented on encryptor.py
> +    if mode.name in ('ENCODE', 'DECODE'):
Стоило сделать как выше

2021-03-31 16:40 UTC, merged